# Trabalho_4

Nome: Gabriel Ogassawaraz de Souza

In [1]:
# inicializando panda e numpy
import pandas as pd
import numpy as np

1. Criar um DataFrame com um dicinário

In [2]:
dados = {
    'Nome': ['João', 'Maria', 'Pedro'],
    'Idade': [25, 30, 27],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Curitiba']
}

In [3]:
df = pd.DataFrame(dados)

In [7]:
df.head()

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     30  Rio de Janeiro
2  Pedro     27        Curitiba

2. Criar um datetime como indice e fazer um DataFrame com 3 colunas

In [19]:
datas = pd.date_range(start='2023-05-20', periods=5, freq='D')

In [20]:
dados = np.random.rand(5, 3)

In [21]:
df = pd.DataFrame(dados, index=datas, columns=['Coluna1', 'Coluna2', 'Coluna3'])

In [22]:
df.head()

             Coluna1   Coluna2   Coluna3
2023-05-20  0.022408  0.455384  0.301470
2023-05-21  0.398574  0.970117  0.776547
2023-05-22  0.075779  0.108318  0.115632
2023-05-23  0.500057  0.109408  0.302864
2023-05-24  0.300286  0.928054  0.862236

3. Criar um DataFrame com numpy da sua escolha

In [23]:
dados_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
colunas = ['A', 'B', 'C']

In [25]:
df = pd.DataFrame(dados_numpy, columns=colunas)

In [26]:
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

4. Criar um datetime de 10 anos com periodo de 10 dias e frequencia

In [35]:
datas = pd.date_range(start='2013', end='2023', freq='10D')

In [36]:
print(datas)

DatetimeIndex(['2013-01-01', '2013-01-11', '2013-01-21', '2013-01-31',
               '2013-02-10', '2013-02-20', '2013-03-02', '2013-03-12',
               '2013-03-22', '2013-04-01',
               ...
               '2022-10-01', '2022-10-11', '2022-10-21', '2022-10-31',
               '2022-11-10', '2022-11-20', '2022-11-30', '2022-12-10',
               '2022-12-20', '2022-12-30'],
              dtype='datetime64[ns]', length=366, freq='10D')